version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "06:00"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
    open-pull-requests-limit: 5
    groups:
      dependencies:
        patterns:
          - "*"
    assignees:
      - "hhftechnology"
    reviewers:
      - "hhftechnology"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "06:00"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
    open-pull-requests-limit: 5
    groups:
      dependencies:
        patterns:
          - "*"
    assignees:
      - "hhftechnology"
    reviewers:
      - "hhftechnology"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
      time: "06:00"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
    open-pull-requests-limit: 5
    groups:
      dependencies:
        patterns:
          - "*"
    assignees:
      - "hhftechnology"
    reviewers:
      - "hhftechnology"
